const fs=require('fs');
const target='src/mu-safety-assistant-v1.50-rc8.3.js';
const modulePath='src/rc8.3-xlsx-functions.js';
const start='/* RC8.3_XLSX_START */';
const end='/* RC8.3_XLSX_END */';
let source=fs.readFileSync(target,'utf8');
const block=start+'\n'+fs.readFileSync(modulePath,'utf8').trim()+'\n'+end+'\n';
const pattern=new RegExp('/\\* RC8\\.3_XLSX_START \\*/[\\s\\S]*?/\\* RC8\\.3_XLSX_END \\*/\\n?');
source=pattern.test(source)?source.replace(pattern,block):source.replace('function openStatisticsModal()',block+'function openStatisticsModal()');
source=source.replace(/v:'V1\.50 RC8\.3(?: XLSX Hotfix 2)?'/,"v:'V1.50 RC8.3 XLSX Hotfix 3'");
source=source.replace(",exportMonth=btn('匯出月報 Excel',0),exportQuarter=btn('匯出季報 Excel',0)",'');
source=source.replace('controls.append(thisMonth,lastMonth,monthInput,exportMonth,exportQuarter,close)','controls.append(thisMonth,lastMonth,monthInput,close)');
source=source.replace("monthInput.onchange=render;exportMonth.onclick=()=>downloadExcelReport('month',monthInput.value);exportQuarter.onclick=()=>downloadExcelReport('quarter',monthInput.value);close.onclick",'monthInput.onchange=render;close.onclick');
const statsButton="let stats=btn('📊 工作統計中心',0);stats.style.width='100%';stats.style.marginTop='8px';stats.setAttribute('data-action','open-statistics');p.appendChild(stats);";
const reportButton="let reports=btn('📊 報表輸出中心',0);reports.style.width='100%';reports.style.marginTop='8px';reports.setAttribute('data-action','open-reports');reports.onclick=e=>{e.preventDefault();e.stopPropagation();openReportCenter()};p.appendChild(reports);";
if(!source.includes(reportButton))source=source.replace(statsButton,statsButton+reportButton);
source=source.replace('let o=L();panel(o);installReportButton() }catch(e)', 'let o=L();panel(o) }catch(e)');
fs.writeFileSync(target,source);
