const fs=require('fs');
const target='src/mu-safety-assistant-v1.50-rc8.4.js';
const modulePath='src/rc8.4-xlsx-functions.js';
const start='/* RC8.4_XLSX_START */';
const end='/* RC8.4_XLSX_END */';
let source=fs.readFileSync('src/mu-safety-assistant-v1.50-rc8.3.js','utf8');
const block=start+'\n'+fs.readFileSync(modulePath,'utf8').trim()+'\n'+end+'\n';
const pattern=new RegExp('/\\* RC8\\.(?:3|4)_XLSX_START \\*/[\\s\\S]*?/\\* RC8\\.(?:3|4)_XLSX_END \\*/\\n?');
source=pattern.test(source)?source.replace(pattern,block):source.replace('function openStatisticsModal()',block+'function openStatisticsModal()');
source=source.replace(/v:'V1\.50 RC8\.(?:3 XLSX Hotfix 3|4 試作版)'/,"v:'V1.50 RC8.4 試作版'");
source=source.replace("['office','辦公室文書／入場作業','辦理工安文件及表單、資料彙整、人員辦證、入場資格及權限申請等行政作業。'],['plan','防護計畫／工程送審資料','製作、修訂及整理施工安全、防護計畫與工程送審相關資料。'],['siteoffice','工務所作業','於工務所辦理工安文件、施工資料整理、現場支援準備及相關行政作業。']", "['office','辦公室／文書作業','辦理工安文件、表單及相關文書作業。'],['siteoffice','工務所／文書作業','於工務所辦理工安文件、施工資料整理及相關文書作業。'],['plan','防護計畫／工程送審資料','製作、修訂及整理施工安全、防護計畫與工程送審相關資料。']");
source=source.replace("lf:'',systemTemplateOverrides", "lf:'',lastDocumentWork:'',systemTemplateOverrides");
source=source.replace("function workLocation(id){id=String(id||'').replace(/^system:/,'');if(['general','followup','supervisor'].includes(id))return 'site';if(['office','plan'].includes(id))return 'office';if(id==='siteoffice')return 'office-site';return null}", "function workLocation(id){id=String(id||'').replace(/^system:/,'');if(['general','followup','supervisor'].includes(id))return 'site';if(['office','plan'].includes(id))return 'office';if(id==='siteoffice')return 'office-site';return null}\nfunction isDocumentWorkTemplate(id){return ['office','siteoffice'].includes(String(id||'').replace(/^system:/,''))}");
source=source.replace("let workPlace=Array.isArray(chosen)?workLocation(chosen[0]):null,place=workPlace,initial=", "let documentWork='';if(Array.isArray(chosen)&&isDocumentWorkTemplate(chosen[0])){let entered=prompt('今天主要做什麼文書作業？',String(o.lastDocumentWork||''));if(entered===null)return;documentWork=String(entered).trim();o.lastDocumentWork=documentWork}let workPlace=Array.isArray(chosen)?workLocation(chosen[0]):null,place=workPlace,initial=");
source=source.replace("let documentWork='';if(Array.isArray(chosen)&&isDocumentWorkTemplate(chosen[0]))", "let documentTemplate=Array.isArray(chosen)&&isDocumentWorkTemplate(chosen[0]),documentWork='';if(documentTemplate)");
source=source.replace("let w=prompt('今日工安工作要項',initial);if(w===null)return", "let w=documentTemplate?chosen[1]:prompt('今日工安工作要項',initial);if(w===null)return");
source=source.replace("workTemplateName:Array.isArray(chosen)?chosen[3]?.baseName||chosen[1]:'自訂內容',workContent:w", "workTemplateName:Array.isArray(chosen)?chosen[3]?.baseName||chosen[1]:'自訂內容',documentWork,workContent:w");
source=source.replace(",exportMonth=btn('匯出月報 Excel',0),exportQuarter=btn('匯出季報 Excel',0)",'');
source=source.replace('controls.append(thisMonth,lastMonth,monthInput,exportMonth,exportQuarter,close)','controls.append(thisMonth,lastMonth,monthInput,close)');
source=source.replace("monthInput.onchange=render;exportMonth.onclick=()=>downloadExcelReport('month',monthInput.value);exportQuarter.onclick=()=>downloadExcelReport('quarter',monthInput.value);close.onclick",'monthInput.onchange=render;close.onclick');
const statsButton="let stats=btn('📊 工作統計中心',0);stats.style.width='100%';stats.style.marginTop='8px';stats.setAttribute('data-action','open-statistics');p.appendChild(stats);";
const reportButton="let reports=btn('📊 報表輸出中心',0);reports.style.width='100%';reports.style.marginTop='8px';reports.setAttribute('data-action','open-reports');reports.onclick=e=>{e.preventDefault();e.stopPropagation();openReportCenter()};p.appendChild(reports);";
if(!source.includes(reportButton))source=source.replace(statsButton,statsButton+reportButton);
source=source.replace('let o=L();panel(o);installReportButton() }catch(e)', 'let o=L();panel(o) }catch(e)');
fs.writeFileSync(target,source);
